config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tasks/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "tasks#index"
  resources :users, only: [:index, :show, :edit, :update]
  resources :customers
  resources :prospects, only: [:index, :show]
  resources :proposals, only: [:index, :show]
  resources :holds, only: [:index, :show]
  resources :losses, only: [:index, :show]
  resources :wins, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :status

  validates :name, :product, :count, presence: true
  validates :status_id, numericality: { other_than: 1 }
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '未提案' },
    { id: 3, name: '提案中' },
    { id: 4, name: '保留' },
    { id: 5, name: '敗退' },
    { id: 6, name: '成約' },
  ]

  include ActiveHash::Associations
  has_many :customers
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :customers
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.all
    @users = User.all
  end
  
  def show
    @users = User.all
    @user = User.find(params[:id])
    @customers = @user.customers
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    if @customer.destroy
      redirect_to customers_path
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customers_path
    end
  end
  private

  def customer_params
    params.require(:customer).permit(:name, :product, :count, :status_id).merge(user_id: current_user.id)
  end
end

app/controllers/holds_controller.rb
class HoldsController < ApplicationController
  def index
    @customers = Customer.all
    @users = User.all
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
    @customers = @user.customers
  end

  def customer_params
    params.require(:customer).permit(:name, :product, :count, :status_id).merge(user_id: current_user.id)
  end
end

app/controllers/losses_controller.rb
class LossesController < ApplicationController
  def index
    @customers = Customer.all
    @users = User.all
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
    @customers = @user.customers
  end

  def customer_params
    params.require(:customer).permit(:name, :product, :count, :status_id).merge(user_id: current_user.id)
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  def index
    @customers = Customer.all
    @users = User.all
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
    @customers = @user.customers
  end

  def customer_params
    params.require(:customer).permit(:name, :product, :count, :status_id).merge(user_id: current_user.id)
  end

end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  def index
    @customers = Customer.all
    @users = User.all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @customers = Customer.all
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @users = User.all
    @user = User.find(params[:id])
    @customers = @user.customers
  end

  def edit
  end

  def update
     if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/wins_controller.rb
class WinsController < ApplicationController
  def index
    @customers = Customer.all
    @users = User.all
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
    @customers = @user.customers
  end

  def customer_params
    params.require(:customer).permit(:name, :product, :count, :status_id).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/holds_helper.rb
module HoldsHelper
end

app/helpers/losses_helper.rb
module LossesHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wins_helper.rb
module WinsHelper
end

app/views/customers/_main.html.erb
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mt-3 mb-3 border-bottom">
            <% if @user %>
              <h1 class="h2"> <%= @user.name %>さんの見込先 </h1>
            <% else %>
              <h1 class="h2"> 宇都宮支店の見込先</h1>
            <% end %>
          
            <div class="btn-toolbar mb-2 mb-md-0">
              <button type="button" class="btn btn-sm btn-outline-secondary">
                <%= link_to '新規見込先登録', new_customer_path, method: :get, class: "text-decoration-none text-black-50" %>
              </button>
            </div>
          </div>

          <div class="table-responsive mt-4">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th></th>
                  <th>顧客名</th>
                  <th>サービス名</th>
                  <th>台数</th>
                  <th>提案状況</th>
                  <th>担当</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% i = 0%>
                <% @customers.each do |customer| %>
                  <tr>
                    <td><%= i += 1  %></td>
                    <td><%= customer.name %> </td>
                    <td><%= customer.product %></td>
                    <td><%= customer.count %></td>
                    <td><%= customer.status.name%></td>
                    <td><%= customer.user.name %></td>
                    <% if user_signed_in? && current_user.id == customer.user_id %>
                    <td> 
                    <div class="btn-group me-2">
                      <button type="button" class="btn btn-sm "><%= link_to '編集', edit_customer_path(customer.id), method: :get, class: "text-decoration-none text-black-50" %> </button>
                      <button type="button" class="btn btn-sm "><%= link_to '削除', customer_path(customer.id), method: :delete, class: "text-decoration-none text-black-50" %> </button>
                    </div>
                    </td>
                    <% else %>
                    <td> 
                    <div class="btn-group me-2">
                    </div>
                    </td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody> 
            </table>
          </div>

        </main>

app/views/customers/index.html.erb
<body>
  
  <div class="container-fluid">
    <div class="row">
      <div class="main">
        <%# ↓↓サイドバー↓↓ %>
        <%= render "shared/side_bar", locals: {users: @users}%>
        <%# ↑↑サイドバー↑↑ %>


<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <%# ↓↓メイン画面の上の方↓↓ %>
          <%= render "customers/main_top" %>
          <%# ↑↑メイン画面の上の方↑↑ %>
          
          <div class="table-responsive mt-4">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th></th>
                  <th>顧客名</th>
                  <th>サービス名</th>
                  <th>台数</th>
                  <th>提案状況</th>
                  <th>担当</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% i = 0%>
                <% @customers.each do |customer| %>
                  <tr>
                    <td><%= i += 1  %></td>
                    <td><%= customer.name %> </td>
                    <td><%= customer.product %></td>
                    <td><%= customer.count %></td>
                    <td><%= customer.status.name%></td>
                    <td><%= customer.user.name %></td>
                    <% if user_signed_in? && current_user.id == customer.user_id %>
                    <td> 
                    <div class="btn-group me-2">
                      <button type="button" class="btn btn-sm "><%= link_to '編集', edit_customer_path(customer.id), method: :get, class: "text-decoration-none text-black-50" %> </button>
                      <button type="button" class="btn btn-sm "><%= link_to '削除', customer_path(customer.id), method: :delete, class: "text-decoration-none text-black-50" %> </button>
                    </div>
                    </td>
                    <% else %>
                    <td> 
                    <div class="btn-group me-2">
                    </div>
                    </td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody> 
            </table>
          </div>
        </main>





        
      </div>
    </div>
  </div>
    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="dashboard.js"></script>
</body>

app/views/customers/show.html.erb
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="main">
        <%# ↓↓サイドバー↓↓ %>
        <%= render "shared/side_bar", locals: {users: @users}%>
        <%# ↑↑サイドバー↑↑ %>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <%# ↓↓メイン画面の上の方↓↓ %>
          <%= render "customers/main_top" %>
          <%# ↑↑メイン画面の上の方↑↑ %>
          
          <div class="table-responsive mt-4">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th></th>
                  <th>顧客名</th>
                  <th>サービス名</th>
                  <th>粗利</th>
                  <th>提案状況</th>
                  <th>担当</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% i = 0%>
                <% @customers.each do |customer| %>
                 <% if customer.status_id == 2 %>
                  <tr>
                    <td><%= i += 1  %></td>
                    <td><%= customer.name %> </td>
                    <td><%= customer.product %></td>
                    <td><%= customer.count %></td>
                    <td><%= customer.status.name%></td>
                    <td><%= customer.user.name %></td>
                    <% if user_signed_in? && current_user.id == customer.user_id %>
                    <td> 
                    <div class="btn-group me-2">
                      <button type="button" class="btn btn-sm "><%= link_to '編集', edit_customer_path(customer.id), method: :get, class: "text-decoration-none text-black-50" %> </button>
                      <button type="button" class="btn btn-sm "><%= link_to '削除', customer_path(customer.id), method: :delete, class: "text-decoration-none text-black-50" %> </button>
                    </div>
                    </td>
                    <% else %>
                    <td> 
                    <div class="btn-group me-2">
                    </div>
                    </td>
                    <% end %>
                  </tr>
                 <% end %>
                <% end %>
              </tbody> 
            </table>
          </div>
        </main>
      </div>
    </div>
  </div>
    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="dashboard.js"></script>
</body>

app/views/holds/index.html.erb
<body>
  
  <div class="container-fluid">
    <div class="row">
      <div class="main">
        <%# ↓↓サイドバー↓↓ %>
        <%= render "shared/side_bar", locals: {users: @users}%>
        <%# ↑↑サイドバー↑↑ %>

    
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <%# ↓↓メイン画面の上の方↓↓ %>
          <%= render "customers/main_top" %>
          <%# ↑↑メイン画面の上の方↑↑ %>
          
          <div class="table-responsive mt-4">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th></th>
                  <th>顧客名</th>
                  <th>サービス名</th>
                  <th>粗利</th>
                  <th>提案状況</th>
                  <th>担当</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% i = 0%>
                <% @customers.each do |customer| %>
                <% if customer.status_id == 4 %>
                  <tr>
                    <td><%= i += 1  %></td>
                    <td><%= customer.name %> </td>
                    <td><%= customer.product %></td>
                    <td><%= customer.count %></td>
                    <td><%= customer.status.name%></td>
                    <td><%= customer.user.name %></td>
                    <% if user_signed_in? && current_user.id == customer.user_id %>
                    <td> 
                    <div class="btn-group me-2">
                      <button type="button" class="btn btn-sm "><%= link_to '編集', edit_customer_path(customer.id), method: :get, class: "text-decoration-none text-black-50" %> </button>
                      <button type="button" class="btn btn-sm "><%= link_to '削除', customer_path(customer.id), method: :delete, class: "text-decoration-none text-black-50" %> </button>
                    </div>
                    </td>
                    <% else %>
                    <td> 
                    <div class="btn-group me-2">
                    </div>
                    </td>
                    <% end %>
                  </tr>
                <% end %>
                <% end %>
              </tbody> 
            </table>
          </div>
        </main>













        
      </div>
    </div>
  </div>
    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="dashboard.js"></script>
</body>

app/views/holds/show.html.erb
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="main">
        <%# ↓↓サイドバー↓↓ %>
        <%= render "shared/side_bar", locals: {users: @users}%>
        <%# ↑↑サイドバー↑↑ %>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <%# ↓↓メイン画面の上の方↓↓ %>
          <%= render "customers/main_top" %>
          <%# ↑↑メイン画面の上の方↑↑ %>
          
          <div class="table-responsive mt-4">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th></th>
                  <th>顧客名</th>
                  <th>サービス名</th>
                  <th>粗利</th>
                  <th>提案状況</th>
                  <th>担当</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% i = 0%>
                <% @customers.each do |customer| %>
                 <% if customer.status_id == 4 %>
                  <tr>
                    <td><%= i += 1  %></td>
                    <td><%= customer.name %> </td>
                    <td><%= customer.product %></td>
                    <td><%= customer.count %></td>
                    <td><%= customer.status.name%></td>
                    <td><%= customer.user.name %></td>
                    <% if user_signed_in? && current_user.id == customer.user_id %>
                    <td> 
                    <div class="btn-group me-2">
                      <button type="button" class="btn btn-sm "><%= link_to '編集', edit_customer_path(customer.id), method: :get, class: "text-decoration-none text-black-50" %> </button>
                      <button type="button" class="btn btn-sm "><%= link_to '削除', customer_path(customer.id), method: :delete, class: "text-decoration-none text-black-50" %> </button>
                    </div>
                    </td>
                    <% else %>
                    <td> 
                    <div class="btn-group me-2">
                    </div>
                    </td>
                    <% end %>
                  </tr>
                 <% end %>
                <% end %>
              </tbody> 
            </table>
          </div>
        </main>
      </div>
    </div>
  </div>
    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="dashboard.js"></script>
</body>

app/views/losses/index.html.erb
<body>
  
  <div class="container-fluid">
    <div class="row">
      <div class="main">
        <%# ↓↓サイドバー↓↓ %>
        <%= render "shared/side_bar", locals: {users: @users}%>
        <%# ↑↑サイドバー↑↑ %>

    
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <%# ↓↓メイン画面の上の方↓↓ %>
          <%= render "customers/main_top" %>
          <%# ↑↑メイン画面の上の方↑↑ %>
          
          <div class="table-responsive mt-4">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th></th>
                  <th>顧客名</th>
                  <th>サービス名</th>
                  <th>粗利</th>
                  <th>提案状況</th>
                  <th>担当</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% i = 0%>
                <% @customers.each do |customer| %>
                <% if customer.status_id == 5 %>
                  <tr>
                    <td><%= i += 1  %></td>
                    <td><%= customer.name %> </td>
                    <td><%= customer.product %></td>
                    <td><%= customer.count %></td>
                    <td><%= customer.status.name%></td>
                    <td><%= customer.user.name %></td>
                    <% if user_signed_in? && current_user.id == customer.user_id %>
                    <td> 
                    <div class="btn-group me-2">
                      <button type="button" class="btn btn-sm "><%= link_to '編集', edit_customer_path(customer.id), method: :get, class: "text-decoration-none text-black-50" %> </button>
                      <button type="button" class="btn btn-sm "><%= link_to '削除', customer_path(customer.id), method: :delete, class: "text-decoration-none text-black-50" %> </button>
                    </div>
                    </td>
                    <% else %>
                    <td> 
                    <div class="btn-group me-2">
                    </div>
                    </td>
                    <% end %>
                  </tr>
                <% end %>
                <% end %>
              </tbody> 
            </table>
          </div>
        </main>













        
      </div>
    </div>
  </div>
    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="dashboard.js"></script>
</body>

app/views/losses/show.html.erb
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="main">
        <%# ↓↓サイドバー↓↓ %>
        <%= render "shared/side_bar", locals: {users: @users}%>
        <%# ↑↑サイドバー↑↑ %>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <%# ↓↓メイン画面の上の方↓↓ %>
          <%= render "customers/main_top" %>
          <%# ↑↑メイン画面の上の方↑↑ %>
          
          <div class="table-responsive mt-4">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th></th>
                  <th>顧客名</th>
                  <th>サービス名</th>
                  <th>粗利</th>
                  <th>提案状況</th>
                  <th>担当</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% i = 0%>
                <% @customers.each do |customer| %>
                 <% if customer.status_id == 5 %>
                  <tr>
                    <td><%= i += 1  %></td>
                    <td><%= customer.name %> </td>
                    <td><%= customer.product %></td>
                    <td><%= customer.count %></td>
                    <td><%= customer.status.name%></td>
                    <td><%= customer.user.name %></td>
                    <% if user_signed_in? && current_user.id == customer.user_id %>
                    <td> 
                    <div class="btn-group me-2">
                      <button type="button" class="btn btn-sm "><%= link_to '編集', edit_customer_path(customer.id), method: :get, class: "text-decoration-none text-black-50" %> </button>
                      <button type="button" class="btn btn-sm "><%= link_to '削除', customer_path(customer.id), method: :delete, class: "text-decoration-none text-black-50" %> </button>
                    </div>
                    </td>
                    <% else %>
                    <td> 
                    <div class="btn-group me-2">
                    </div>
                    </td>
                    <% end %>
                  </tr>
                 <% end %>
                <% end %>
              </tbody> 
            </table>
          </div>
        </main>
      </div>
    </div>
  </div>
    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="dashboard.js"></script>
</body>

app/views/proposals/index.html.erb
<body>
  
  <div class="container-fluid">
    <div class="row">
      <div class="main">
        <%# ↓↓サイドバー↓↓ %>
        <%= render "shared/side_bar", locals: {users: @users}%>
        <%# ↑↑サイドバー↑↑ %>

    
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <%# ↓↓メイン画面の上の方↓↓ %>
          <%= render "customers/main_top" %>
          <%# ↑↑メイン画面の上の方↑↑ %>
          
          <div class="table-responsive mt-4">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th></th>
                  <th>顧客名</th>
                  <th>サービス名</th>
                  <th>粗利</th>
                  <th>提案状況</th>
                  <th>担当</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% i = 0%>
                <% @customers.each do |customer| %>
                <% if customer.status_id == 3 %>
                  <tr>
                    <td><%= i += 1  %></td>
                    <td><%= customer.name %> </td>
                    <td><%= customer.product %></td>
                    <td><%= customer.count %></td>
                    <td><%= customer.status.name%></td>
                    <td><%= customer.user.name %></td>
                    <% if user_signed_in? && current_user.id == customer.user_id %>
                    <td> 
                    <div class="btn-group me-2">
                      <button type="button" class="btn btn-sm "><%= link_to '編集', edit_customer_path(customer.id), method: :get, class: "text-decoration-none text-black-50" %> </button>
                      <button type="button" class="btn btn-sm "><%= link_to '削除', customer_path(customer.id), method: :delete, class: "text-decoration-none text-black-50" %> </button>
                    </div>
                    </td>
                    <% else %>
                    <td> 
                    <div class="btn-group me-2">
                    </div>
                    </td>
                    <% end %>
                  </tr>
                <% end %>
                <% end %>
              </tbody> 
            </table>
          </div>
        </main>













        
      </div>
    </div>
  </div>
    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="dashboard.js"></script>
</body>