config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tasks/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "tasks#index"
  resources :users, only: [:index, :show, :edit, :update]
  resources :customers
  resources :prospects, only: [:index, :show]
  resources :proposals, only: [:index, :show]
  resources :holds, only: [:index, :show]
  resources :losses, only: [:index, :show]
  resources :wins, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :status

  validates :name, :product, :count, presence: true
  validates :status_id, numericality: { other_than: 1 }
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '未提案' },
    { id: 3, name: '提案中' },
    { id: 4, name: '保留' },
    { id: 5, name: '敗退' },
    { id: 6, name: '成約' },
  ]

  include ActiveHash::Associations
  has_many :customers
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :customers
  validates :name, presence: true
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.all
    @users = User.all
  end
  
  def show
    @users = User.all
    @user = User.find(params[:id])
    @customers = @user.customers
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    if @customer.destroy
      redirect_to customers_path
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customers_path
    end
  end
  private

  def customer_params
    params.require(:customer).permit(:name, :product, :count, :status_id).merge(user_id: current_user.id)
  end
end

app/controllers/holds_controller.rb
class HoldsController < ApplicationController
  def index
    @customers = Customer.all
    @users = User.all
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
    @customers = @user.customers
  end

  def customer_params
    params.require(:customer).permit(:name, :product, :count, :status_id).merge(user_id: current_user.id)
  end
end

app/controllers/losses_controller.rb
class LossesController < ApplicationController
  def index
    @customers = Customer.all
    @users = User.all
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
    @customers = @user.customers
  end

  def customer_params
    params.require(:customer).permit(:name, :product, :count, :status_id).merge(user_id: current_user.id)
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  def index
    @customers = Customer.all
    @users = User.all
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
    @customers = @user.customers
  end

  def customer_params
    params.require(:customer).permit(:name, :product, :count, :status_id).merge(user_id: current_user.id)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @customers = Customer.all
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @users = User.all
    @user = User.find(params[:id])
    @customers = @user.customers
  end

  def edit
  end

  def update
     if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/wins_controller.rb
class WinsController < ApplicationController
  def index
    @customers = Customer.all
    @users = User.all
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
    @customers = @user.customers
  end

  def customer_params
    params.require(:customer).permit(:name, :product, :count, :status_id).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/holds_helper.rb
module HoldsHelper
end

app/helpers/losses_helper.rb
module LossesHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wins_helper.rb
module WinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
      <%= link_to 'Progress', root_path,class: "navbar-brand col-md-3 col-lg-2 me-0 px-3" %>
        <ul class="nav px-5">
          <% if user_signed_in? %>
            <li class="nav-item text-nowrap m-2"> <%= link_to current_user.name, edit_user_path(current_user),class:  "text-decoration-none text-white"%> </li>
            <li class="nav-item text-nowrap m-2"> <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class:  "text-decoration-none text-white" %> </li>
          <% else %>
            <li class="nav-item text-nowrap m-2"> <%= link_to 'ログイン', new_user_session_path, class:  "text-decoration-none text-white" %></li>
            <li class="nav-item text-nowrap m-2"> <%= link_to '新規登録', new_user_registration_path, class:  "text-decoration-none text-white" %></li>
          <% end %>
        </ul>
    </header>
    <%= yield %>
  </body>
</html>

app/views/shared/_main_index.html.erb
<div class="card__wrapper ">

          <div class="card" style="width: 18rem;">
            <div class="card-header ">
              <% if @user %>
               <h3 class="text-center"> <%= link_to '見込件数', prospect_path(@user.id), method: :get, class: "text-decoration-none"%> </h3>
              <% else %>
               <h3 class="text-center"> <%= link_to '見込件数', prospects_path, method: :get, class: "text-decoration-none"%> </h3>
              <% end %>
            </div>
            <div class="card-body">
              <h1 class="display-1"> 
                 <% count = 0 %>
                 <% @customers.each do |customer| %>
                    <% if customer.status_id == 2 %>
                      <%  count += 1 %>
                    <% end %>
                 <% end %>
                 <%= count %> 
              </h1>
            </div>
            <div class="card-footer">
              <h5 class="text-center"> 目標 30 </h5>
            </div>
          </div>
          

          <div class="card" style="width: 18rem;">
            <div class="card-header">
              <% if @user %>
               <h3 class="text-center"> <%= link_to '提案中', proposal_path(@user.id), method: :get, class: "text-decoration-none"%> </h3>
              <% else %>
               <h3 class="text-center"> <%= link_to '提案中', proposals_path, method: :get, class: "text-decoration-none"%> </h3>
              <% end %>
            </div>
            <div class="card-body">
              <h1 class="display-1"> 
                 <% count = 0 %>
                    <% @customers.each do |customer| %>
                        <% if customer.status_id == 3 %>
                          <%  count += 1 %>
                        <% end %>
                    <% end %>
                 <%= count %> 
              </h1>
            </div>
            <div class="card-footer">
              <h5 class="text-center"> 目標 10 </h5>
            </div>
          </div>

          <div class="card" style="width: 18rem;">
            <div class="card-header">
              <% if @user %>
               <h3 class="text-center"> <%= link_to '保留', hold_path(@user.id), method: :get, class: "text-decoration-none"%> </h3>
              <% else %>
               <h3 class="text-center"> <%= link_to '保留', holds_path, method: :get, class: "text-decoration-none"%> </h3>
              <% end %>
            </div>
            <div class="card-body">
              <h1 class="display-1">
                 <% count = 0 %>
                   <% @customers.each do |customer| %>
                       <% if customer.status_id == 4 %>
                         <%  count += 1 %>
                       <% end %>
                   <% end %>
                 <%= count %> 
              </h1>
            </div>
            <div class="card-footer">
              <h5 class="text-center">目標 - </h5>
            </div>
          </div>

          <div class="card" style="width: 18rem;">
            <div class="card-header">
              <% if @user %>
               <h3 class="text-center"> <%= link_to '敗退件数', loss_path(@user.id), method: :get, class: "text-decoration-none"%> </h3>
              <% else %>
               <h3 class="text-center"> <%= link_to '敗退件数', losses_path, method: :get, class: "text-decoration-none"%> </h3>
              <% end %>
            </div>
            <div class="card-body">
              <h1 class="display-1">
                 <% count = 0 %>
                   <% @customers.each do |customer| %>
                       <% if customer.status_id == 5 %>
                         <%  count += 1 %>
                       <% end %>
                   <% end %>
                 <%= count %> 
              </h1>
            </div>
            <div class="card-footer">
              <h5 class="text-center">目標 - </h5>
            </div>
          </div>

          <div class="card" style="width: 18rem;">
            <div class="card-header">
              <% if @user %>
               <h3 class="text-center"> <%= link_to '成約件数', win_path(@user.id), method: :get, class: "text-decoration-none"%> </h3>
              <% else %>
               <h3 class="text-center"> <%= link_to '成約件数', wins_path, method: :get, class: "text-decoration-none"%> </h3>
              <% end %>
            </div>
            <div class="card-body">
              <h1 class="display-1">
                 <% count = 0 %>
                   <% @customers.each do |customer| %>
                       <% if customer.status_id == 6 %>
                         <%  count += 1 %>
                       <% end %>
                   <% end %>
                 <%= count %> 
              </h1>
            </div>
            <div class="card-footer">
              <% noruma = 100 %>
              <h5 class="text-center"> 目標 <%= noruma %></h5>
            </div>
          </div>

          <div class="card" style="width: 18rem;">
            <div class="card-header">
              <h3 class="text-center text-primary"> 進捗率</h3>
            </div>
            <div class="card-body">
              <h1 class="display-1">
                  <%= (100 * count/noruma).to_i %>
                  <a class="h3 text-decoration-none text-body">%</a>
              </h1>
             </div>
             <div class="card-footer">
               <h5 class="text-center">目標 100%</h5>
             </div>
           </div>
          </div>

app/views/shared/_new_customer_button.html.erb
<div class="btn-toolbar mb-2 mb-md-0">
  <button type="button" class="btn btn-sm btn-outline-secondary">
    <%= link_to '新規見込先登録', new_customer_path, method: :get, class: "text-decoration-none text-black-50" %>
  </button>
</div>

app/views/shared/_side_bar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
  <div class="position-sticky pt-3">
    <ul class="nav flex-column">
      <li class="nav-item">
        <ul class="nav flex">
          <li>
            <a class="text-secondary" >
              <svg xmlns="http://www.w3.org/2000/svg" width="32" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
            </a>
          </li>
          <li>
              <%= link_to '宇都宮支店', root_path, class: "nav-link h4 text-secondary" %> 
          </li>
        </ul>  
      </li>
      <% @users.each do |user| %>
      <li class="nav-item">
        <ul class="nav flex">
         <li>
           <a class="nav-link text-secondary">
              <svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
           </a>
         </li>
         <li>
           <%= link_to user.name + "さん", user_path(user.id), class: "nav-link text-secondary h4" %> 
         </li>
        </ul>
      </li>
      <% end %>
    </ul>
  </div>
</nav>